// pages/qr.js
import dynamic from "next/dynamic";
import { useState, useRef } from "react";
const QRCode = dynamic(() => import("react-qr-code"), { ssr: false });
import { jwtSign } from "../lib/jwtClient";

export default function QrPage() {
  const [storeCode, setStoreCode] = useState("mgi");
  const [tableNumber, setTableNumber] = useState("A02");
  const [url, setUrl] = useState("");
  const [token, setToken] = useState("");
  const [loading, setLoading] = useState(false);

  // ref to the container that holds the SVG generated by react-qr-code
  const qrRef = useRef(null);

  const handleGenerate = async (e) => {
    e?.preventDefault();
    setLoading(true);

    try {
      const secret = process.env.NEXT_PUBLIC_JWT_SECRET;
      const baseUrl = process.env.NEXT_PUBLIC_URL_UAT || process.env.NEXT_PUBLIC_URL_DEV;

      if (!secret) throw new Error("Missing NEXT_PUBLIC_JWT_SECRET in .env.local");
      if (!baseUrl) throw new Error("Missing URL env");

      const payload = { storeCode: storeCode.trim(), tableNumber: tableNumber.trim() };
      const tok = await jwtSign(payload, secret);

      const finalUrl = `${baseUrl}/order?token=${encodeURIComponent(tok)}`;
      setToken(tok);
      setUrl(finalUrl);
    } catch (err) {
      alert("Generate error: " + (err.message || err));
    } finally {
      setLoading(false);
    }
  };

  // download raw SVG file
  const handleDownloadSVG = () => {
    if (!url) return alert("Generate QR terlebih dahulu");
    const svgEl = qrRef.current?.querySelector("svg");
    if (!svgEl) return alert("QR SVG tidak ditemukan");

    // serialize SVG
    const serializer = new XMLSerializer();
    let svgStr = serializer.serializeToString(svgEl);

    // add name spaces if missing (better compatibility)
    if (!svgStr.match(/^<svg[^>]+xmlns="/)) {
      svgStr = svgStr.replace(/^<svg/, '<svg xmlns="http://www.w3.org/2000/svg"');
    }
    if (!svgStr.match(/^<svg[^>]+"http:\/\/www\.w3\.org\/1999\/xlink"/)) {
      svgStr = svgStr.replace(/^<svg/, '<svg xmlns:xlink="http://www.w3.org/1999/xlink"');
    }

    const blob = new Blob([svgStr], { type: "image/svg+xml;charset=utf-8" });
    const filename = `qr-${storeCode || "store"}-${tableNumber || "table"}.svg`;
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(link.href);
  };

  // convert SVG -> PNG using canvas then download
  const handleDownloadPNG = async () => {
    if (!url) return alert("Generate QR terlebih dahulu");
    const svgEl = qrRef.current?.querySelector("svg");
    if (!svgEl) return alert("QR SVG tidak ditemukan");

    const serializer = new XMLSerializer();
    let svgStr = serializer.serializeToString(svgEl);

    if (!svgStr.match(/^<svg[^>]+xmlns="/)) {
      svgStr = svgStr.replace(/^<svg/, '<svg xmlns="http://www.w3.org/2000/svg"');
    }
    if (!svgStr.match(/^<svg[^>]+"http:\/\/www\.w3\.org\/1999\/xlink"/)) {
      svgStr = svgStr.replace(/^<svg/, '<svg xmlns:xlink="http://www.w3.org/1999/xlink"');
    }

    // add background white to avoid transparent bg when saving
    // insert rect as first child
    svgStr = svgStr.replace(/(<svg[^>]*>)/, `$1<rect width="100%" height="100%" fill="#ffffff"/>`);

    const svgBlob = new Blob([svgStr], { type: "image/svg+xml;charset=utf-8" });
    const urlBlob = URL.createObjectURL(svgBlob);

    try {
      const img = new Image();
      // avoid CORS taint: SVG created locally should be fine
      img.onload = () => {
        const canvas = document.createElement("canvas");
        // set canvas size to SVG's width/height or a default scale
        const bbox = svgEl.getBBox();
        // fallback if bbox is zero
        const w = bbox.width || 220;
        const h = bbox.height || 220;
        // higher resolution: multiply by scale (e.g., 4)
        const scale = 4;
        canvas.width = w * scale;
        canvas.height = h * scale;
        const ctx = canvas.getContext("2d");
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        // draw image scaled to canvas
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

        canvas.toBlob((blob) => {
          if (!blob) return alert("Gagal membuat gambar PNG");
          const filename = `qr-${storeCode || "store"}-${tableNumber || "table"}.png`;
          const link = document.createElement("a");
          link.href = URL.createObjectURL(blob);
          link.download = filename;
          document.body.appendChild(link);
          link.click();
          link.remove();
          URL.revokeObjectURL(link.href);
        }, "image/png");
        URL.revokeObjectURL(urlBlob);
      };
      img.onerror = (e) => {
        URL.revokeObjectURL(urlBlob);
        alert("Gagal memuat SVG untuk konversi ke PNG");
      };
      img.src = urlBlob;
    } catch (err) {
      URL.revokeObjectURL(urlBlob);
      alert("Error saat convert: " + (err.message || err));
    }
  };

  return (
    <div style={{ padding: 20, fontFamily: "system-ui, Arial" }}>
      <h2>QR JWT Generator</h2>
      <form onSubmit={handleGenerate} style={{ display: "grid", gap: 8, maxWidth: 520 }}>
        <label>
          Store Code
          <input value={storeCode} onChange={(e) => setStoreCode(e.target.value)} style={{ width: "100%", padding: 8 }} />
        </label>
        <label>
          Table Number
          <input value={tableNumber} onChange={(e) => setTableNumber(e.target.value)} style={{ width: "100%", padding: 8 }} />
        </label>
        <div style={{ display: "flex", gap: 8 }}>
          <button type="submit" disabled={loading}>{loading ? "Generating..." : "Generate QR"}</button>
          <button type="button" onClick={() => { setStoreCode(""); setTableNumber(""); setUrl(""); setToken(""); }}>Reset</button>
        </div>
      </form>

      <div style={{ marginTop: 20, display: "flex", gap: 16 }}>
        <div style={{ padding: 12, background: "#fff", border: "1px solid #eee" }} ref={qrRef}>
          {url ? <QRCode value={url} size={220} /> : <div style={{ width: 220, height: 220, display: "flex", alignItems: "center", justifyContent: "center", color: "#999" }}>QR will appear here</div>}
        </div>

        <div style={{ flex: 1 }}>
          <div>
            <label>Generated URL</label>
            <input readOnly value={url} style={{ width: "100%", padding: 8 }} />
          </div>

          <div style={{ marginTop: 8 }}>
            <label>Token</label>
            <textarea readOnly value={token} style={{ width: "100%", height: 120 }} />
          </div>

          <div style={{ marginTop: 8, display: "flex", gap: 8, flexWrap: "wrap" }}>
            <button onClick={() => { if (!url) return alert("Generate first"); navigator.clipboard.writeText(url).then(() => alert("Copied URL")); }}>Copy URL</button>
            <button onClick={() => { if (!token) return alert("Generate first"); navigator.clipboard.writeText(token).then(() => alert("Copied Token")); }}>Copy Token</button>

            {/* Download buttons */}
            <button style={{ marginLeft: 8 }} onClick={handleDownloadSVG}>Download SVG</button>
            <button style={{ marginLeft: 8 }} onClick={handleDownloadPNG}>Download PNG</button>
          </div>
        </div>
      </div>
    </div>
  );
}
